import type { Metadata } from "next";
import { Saira } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";

const saira = Saira({
	subsets: ["latin"],
	weight: ["600", "500", "400", "300"],
});

export const metadata: Metadata = {
	title: "Capputeeno",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="pt-BR">
			<body className={saira.className}>
				<Header />
				{children}
			</body>
		</html>
	);
}
